#!/bin/bash

Z=~/src/zones
export PYTHONPATH=$PYTHONPATH:$Z

authbind --deep ~pypy/bin/twistd \
    --logfile ~/run/twistd.log \
    --pidfile ~/log/twistd.pid \
    dns \
    --pyzone $Z/twistedmatrix.com \
    --pyzone $Z/divunal.com \
    --pyzone $Z/intarweb.us \
    --pyzone $Z/ynchrono.us \
    --pyzone $Z/divmod.com \
    --pyzone $Z/divmod.org
