#!/bin/bash

Z=~/Names/Zones
export PYTHONPATH=$PYTHONPATH:$Z

authbind --deep ~pypy/bin/twistd \
    --logfile ~/Run/twistd.log \
    --pidfile ~/Run/twistd.pid \
    dns \
    --pyzone $Z/twistedmatrix.com \
    --pyzone $Z/divunal.com \
    --pyzone $Z/intarweb.us \
    --pyzone $Z/ynchrono.us \
    --pyzone $Z/divmod.com \
    --pyzone $Z/divmod.org
